services:
  web:
    build: .
    command: bin/rails server -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/quadro_vagas_development
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: quadro_vagas_development
volumes:
  pg_data: